spring:
  profiles.active: dev
  application.name: cakesShop
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
server.port: 9000

storage.address: http://localhost:9000
order.address: http://localhost:9000